# Dev Config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base  # Core

namespace: sir-dev  # Development namespace

labels:
  - includeSelectors: false
    pairs:
      environment: development

patches:
  # Scale down
  - target:
      kind: Deployment
      name: flask-app-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1  # Single pod

  # Light resources
  - target:
      kind: Deployment
      name: flask-app-deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "50m"      # Min CPU
            memory: "64Mi"  # Min RAM
          limits:
            cpu: "200m"     # Cap CPU
            memory: "128Mi" # Cap RAM